-- CreateTable
CREATE TABLE `URL` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `full` VARCHAR(191) NOT NULL,
    `short` VARCHAR(191) NOT NULL,
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `URL_short_key`(`short`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
